-- MySQL Script generated by MySQL Workbench
-- 11/24/16 18:45:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nascimento` DATETIME NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `rg` INT NOT NULL,
  `celular` INT NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `Afiliado_matricula` INT NOT NULL,
  PRIMARY KEY (`cpf`, `Afiliado_matricula`),
  INDEX `fk_Dependente_Afiliado1_idx` (`Afiliado_matricula` ASC),
  CONSTRAINT `fk_Dependente_Afiliado1`
    FOREIGN KEY (`Afiliado_matricula`)
    REFERENCES `mydb`.`Afiliado` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Afiliado` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nascimento` DATETIME NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `rg` INT NOT NULL,
  `cpf` INT NOT NULL,
  `celular` INT NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DAS` (
  `Afiliado_matricula` INT NOT NULL,
  `porcentagem` DECIMAL(3,2) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Afiliado_matricula`),
  CONSTRAINT `fk_DAS_Afiliado1`
    FOREIGN KEY (`Afiliado_matricula`)
    REFERENCES `mydb`.`Afiliado` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RCS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RCS` (
  `Afiliado_matricula` INT NOT NULL,
  `porcentagem` DECIMAL(3,2) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Afiliado_matricula`),
  CONSTRAINT `fk_RCS_Afiliado1`
    FOREIGN KEY (`Afiliado_matricula`)
    REFERENCES `mydb`.`Afiliado` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Convenio` (
  `idConvenio` INT NOT NULL,
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  `mensalidade` VARCHAR(45) NOT NULL,
  `DAS_Afiliado_matricula` INT NOT NULL,
  `RCS_Afiliado_matricula` INT NOT NULL,
  INDEX `fk_Convenio_DAS1_idx` (`DAS_Afiliado_matricula` ASC),
  INDEX `fk_Convenio_RCS1_idx` (`RCS_Afiliado_matricula` ASC),
  PRIMARY KEY (`idConvenio`),
  CONSTRAINT `fk_Convenio_DAS1`
    FOREIGN KEY (`DAS_Afiliado_matricula`)
    REFERENCES `mydb`.`DAS` (`Afiliado_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Convenio_RCS1`
    FOREIGN KEY (`RCS_Afiliado_matricula`)
    REFERENCES `mydb`.`RCS` (`Afiliado_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FolhaDePagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FolhaDePagamento` (
  `idPagamento` INT NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `data` DATETIME NOT NULL,
  `adicional` DECIMAL(10,2) NULL,
  `Afiliado_matricula` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Afiliado_matricula`),
  INDEX `fk_FolhaDePagamento_Afiliado1_idx` (`Afiliado_matricula` ASC),
  CONSTRAINT `fk_FolhaDePagamento_Afiliado1`
    FOREIGN KEY (`Afiliado_matricula`)
    REFERENCES `mydb`.`Afiliado` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nascimento` DATETIME NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `rg` INT NOT NULL,
  `celular` INT NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `Afiliado_matricula` INT NOT NULL,
  PRIMARY KEY (`cpf`, `Afiliado_matricula`),
  INDEX `fk_Dependente_Afiliado1_idx` (`Afiliado_matricula` ASC),
  CONSTRAINT `fk_Dependente_Afiliado1`
    FOREIGN KEY (`Afiliado_matricula`)
    REFERENCES `mydb`.`Afiliado` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependente_has_Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente_has_Convenio` (
  `Dependente_cpf` INT NOT NULL,
  `Convenio_idConvenio` INT NOT NULL,
  PRIMARY KEY (`Dependente_cpf`, `Convenio_idConvenio`),
  INDEX `fk_Dependente_has_Convenio_Convenio1_idx` (`Convenio_idConvenio` ASC),
  INDEX `fk_Dependente_has_Convenio_Dependente1_idx` (`Dependente_cpf` ASC),
  CONSTRAINT `fk_Dependente_has_Convenio_Dependente1`
    FOREIGN KEY (`Dependente_cpf`)
    REFERENCES `mydb`.`Dependente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dependente_has_Convenio_Convenio1`
    FOREIGN KEY (`Convenio_idConvenio`)
    REFERENCES `mydb`.`Convenio` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Afiliado_has_Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Afiliado_has_Convenio` (
  `Afiliado_matricula` INT NOT NULL,
  `Convenio_idConvenio` INT NOT NULL,
  PRIMARY KEY (`Afiliado_matricula`, `Convenio_idConvenio`),
  INDEX `fk_Afiliado_has_Convenio_Convenio1_idx` (`Convenio_idConvenio` ASC),
  INDEX `fk_Afiliado_has_Convenio_Afiliado1_idx` (`Afiliado_matricula` ASC),
  CONSTRAINT `fk_Afiliado_has_Convenio_Afiliado1`
    FOREIGN KEY (`Afiliado_matricula`)
    REFERENCES `mydb`.`Afiliado` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Afiliado_has_Convenio_Convenio1`
    FOREIGN KEY (`Convenio_idConvenio`)
    REFERENCES `mydb`.`Convenio` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Devolucao_RCS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Devolucao_RCS` (
  `valor` DECIMAL(10,2) NOT NULL,
  `data` DATETIME NOT NULL,
  `RCS_Afiliado_matricula` INT NOT NULL,
  PRIMARY KEY (`RCS_Afiliado_matricula`),
  CONSTRAINT `fk_Devolucao_RCS_RCS1`
    FOREIGN KEY (`RCS_Afiliado_matricula`)
    REFERENCES `mydb`.`RCS` (`Afiliado_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Devolucao_DAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Devolucao_DAS` (
  `valor` DECIMAL(10,2) NOT NULL,
  `data` DATETIME NOT NULL,
  `DAS_Afiliado_matricula` INT NOT NULL,
  PRIMARY KEY (`DAS_Afiliado_matricula`),
  CONSTRAINT `fk_Devolucao_DAS_DAS1`
    FOREIGN KEY (`DAS_Afiliado_matricula`)
    REFERENCES `mydb`.`DAS` (`Afiliado_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
